### ISSUE TITLE
uploading a rar to github

### ISSUE THREAD

**Issue by prvvvvvv** [teamfortress1/immortal2018#1]
are you RARted?

**Comment by teamfortress1** [comment]
![image](https://user-images.githubusercontent.com/67800564/155772906-f730738e-e6e9-43cf-bc89-ba30a90f1191.png)
yo u so fuckin autistic no cap

**Comment by prv8238** [comment]
YEP LETS JUST UPLOAD FROM DA BROWSER :DD:D

**Comment by prvvvvvv** [comment]
pro tip: install git :D:D:D

**Comment by teamfortress1** [comment]
as i would like
